# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 06:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='_to_user',
        ),
        migrations.AddField(
            model_name='message',
            name='_to_user',
            field=models.ManyToManyField(related_name='_message__to_user_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
