# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_auto_20170303_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iser_id', models.ManyToManyField(related_name='_additive_iser_id_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='_to_user',
            field=models.ManyToManyField(related_name='_message__to_user_+', to='app1.Additive'),
        ),
    ]
