# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_auto_20170303_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additive',
            name='iser_id',
        ),
        migrations.AddField(
            model_name='additive',
            name='user_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
