# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20170303_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='_to_user',
        ),
        migrations.AddField(
            model_name='message',
            name='_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app1.Additive'),
        ),
    ]
