# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20170303_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='user_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app1.Additive'),
        ),
    ]
